package main

import "fmt"

func main() {
	var sum int
	for _, sack := range input {
		left := make(map[byte]struct{})
		double := make(map[byte]struct{})
		for i := 0; i < len(sack); i++ {
			if i < len(sack)/2 {
				left[sack[i]] = struct{}{}
			} else {
				if _, ok := left[sack[i]]; ok {
					double[sack[i]] = struct{}{}
				}
			}
		}
		for r := range double {
			if r >= 'a' && r <= 'z' {
				sum += int(r - 'a' + 1)
			} else {
				sum += int(r - 'A' + 27)
			}
		}
	}
	fmt.Println(sum)

	var sum2 int
nextSet:
	for i := 0; i < len(input); i += 3 {
		a, b := make(map[byte]struct{}), make(map[byte]struct{})
		for j := 0; j < len(input[i]); j++ {
			a[input[i][j]] = struct{}{}
		}
		for j := 0; j < len(input[i+1]); j++ {
			b[input[i+1][j]] = struct{}{}
		}
		for j := 0; j < len(input[i+2]); j++ {
			r := input[i+2][j]
			_, oka := a[r]
			_, okb := b[r]
			if oka && okb {
				if r >= 'a' && r <= 'z' {
					sum2 += int(r - 'a' + 1)
				} else {
					sum2 += int(r - 'A' + 27)
				}
				continue nextSet
			}
		}
	}
	fmt.Println(sum2)
}

var input = []string{
	"qFdBBvtHHfvRlfvsqldvqjPpQmnQmjnjjjTRTLGRNG",
	"ZCWhhCsJCzSJzSbzgsmPTGNNPPNGjgLTLjgn",
	"WJZsbJMwJcszJcScwhVltFwBFBlqddvFdHDfqq",
	"crtTsGTtqFThGQGCrsjTwdNJwpRdnJJwffRClpSf",
	"PWVBPVHLvHHVgvZWBzmPpnfRSJJRQnSRflRPSNSl",
	"gmzBzDgzmZQWLDLLgVmDrqGhsscrqDMGhcqtqcFr",
	"HsbcdVrsbVbcLfPqqQsqqtPj",
	"mMBFzZRnmFMRBDnDFBGZDGdDqLjtdQtPtgfPfttgtqgq",
	"BZvZZdJMBFdJhSvhbhchcHll",
	"GNRSqRfcNTpfGCcqjfzBpDQPWBzgDpQsPWzW",
	"rrSdnVHlbMdLdBDzgtBtBmQt",
	"rbFwwnLFLFwlMLrFwFhMVLrGNSTfZTRhfTqjGJRRZTCNcf",
	"QWTnQCnWNNWmTnSPQwmqDbcscbpcjPjVPbrjpq",
	"vJhzZNlNNgdzgzJdlGzHHcHDpjsHqrvbVrbvrD",
	"RzRdRlhLgtCwCWSLnN",
	"SFTJFTTwTVVSJBnSTdvNNfWbZCZWNZCNNhBv",
	"srLrcHDcsjtLcLLcrLctjlcvbDNhmWCvNhZWGZZhNvhZmb",
	"rclgtMPrrSgVTgJCng",
	"DbrhDzcDffbzNbZvZWSSqSTNSVWv",
	"gCPltPmCPglFnPFwtGPhGPwTCTdZZWZVRvWqdRqVVdTdvR",
	"hLBhlmlstcffBzrpfj",
	"wFLLmhMfwZLDwmMNRhZwRLDvJgldbJHPdQvcQHHJQPgH",
	"bjrVrTSSJdQHcVll",
	"CGCSsCCBpspBrqbSttpbqWmWZRmfFRZhZMNNLFqFLm",
	"zWGjjBHGjzzTWMjhtDDWtPPlJZPJpvqQrmZTqQQpmr",
	"RFbVLcBVLRcRVcCsCCqvpCZqmplqQJmPrlvQ",
	"FLNRRSSRgScSVLLLNdFdwjHjnftBtGMgMjzHgzjWjj",
	"znVSqnqbqzSbzTHqDDZmlcFcnhDMnDmn",
	"LtjsvdvLJdjfFwRRCCMlChwCpMcclCcZ",
	"LgvjjfjFQVgNTgWq",
	"SJRJRFFCMSsGRMMwtZJRCVTgqgTVgTBCVpjTjmmWlB",
	"ccvnnpnDVqTcBVTV",
	"vPHprdHdpnzHSMsSrMRZJGws",
	"GddGrcGNHnGvnCHddvCSWqTSWsTwTWShbHlhhb",
	"gDPzLRVZgQfpRRFQDDVFDfzhSzsTBqqqnqbhnWTSSlST",
	"QVFfFgRQQgLtgffZRfpFPfntjrcrjCmtCdMMmjMdJJJNtm",
	"jjmNcpGCNmDqqsBfnZnGGGRLsZ",
	"lrmlVWlQQtWllgtbQVrWBnZsJgsRLfZLhZBBBffL",
	"rWMVQtrFlbFlSSMHVSdHHNHdcdDcddzppzzm",
	"bTpjpjcVTLmphbLppJwqzqwJLqqzzzgRLJ",
	"sdHNbrvNHrqPvZZZPRww",
	"bNQCrCNtNsSlhffhVhpVWFCW",
	"lpNnpMMZZDbNbnBjcrbjvScFmbGj",
	"wqhdqVqdscrjdLsv",
	"HQftVqWCfhwqtCCjWwfqzzVPZRJQgMlggZMMMZTNMNTnNRTN",
	"fvvGbFtVmtTwgtMT",
	"WcCcClzPCCcczJJScPWWZzBDmwbhBBHSghgDDMTHMDBD",
	"nWPljWzZWnbcbRsNFjFFdFdVjFsj",
	"NQrcLNmQGRfGLHHLZgbbnpjZJJJndbgnlv",
	"DWtThDWtzzhltWTwjbdpvjbgqjgg",
	"VtSPFWtBPBFSFBWCStshWBmlRfHfMRcfQLQLLlmCrCcN",
	"pbmwqJnqSJVwwDPCjZZzrZfD",
	"QtssBTvNdNvNtQvQGpGhdjPjDjczZDfjhgPPDcgjgr",
	"GltptQpMGNNpRWlWFVFHJFHLWH",
	"ZLLsDGGVhZcQQLhrLshrVFwHnWqJnWMnJJJnqfWfGn",
	"jMlPdTlPlgCgFpngFWFnJfpw",
	"TlTNbdSSTSTmTjPMTCdBPjBMrLDczsZcNrDhRNDRQRLLRVVz",
	"HDLpBqDVVTvwGDDNRT",
	"PlVWjfhsPMMmWtlFNTrhrrvCCCTNNbvw",
	"lsglfgVJmsfMjJfSqSzdZnLgqcnLnp",
	"pfCDJWBpfDffpJLgQJzzVzNrgNgNgNhNzmVr",
	"ZnnGZbGTPZnsnRFdTlbrwdrNzrrmmWwmwVwttH",
	"GbPGRvTnZljWnpqSMMCjqJQSCf",
	"ZgnFgwggznFrfrwfHhNMMr",
	"pctLCLRhPHBLMLWfBL",
	"JJcdJcQCCJmQJppmlgndnFslsVnsvghZ",
	"WpMgTppWGSWWJmJDpJcJJhqm",
	"zZzjZNHvNjPvNsbZLbRLzsPcqhVJSVttdwhwmdRhtdJRVd",
	"sLbvvCZCPSSSbbPfNlQQTQGBllCTnMnWQn",
	"fwbwswddwSbBfDBggMBPDPhHcPWDmhHhmWnWPC",
	"FQFlzLCzQTlrTTzvltFqFrmhPHjnhhnnchcJWcRRmRRq",
	"lpLzlFZzCltrTNlTztQLZfSMGBNdSBVwbBNVSMSbVs",
	"FMmgbTFdgLSgFQdjrRPrQBPDdj",
	"ZqqWRvsfGrrPvvPC",
	"wZzwnqccRwRNNpRSMztSMMFbgzLTFS",
	"qTwBPfTfqQDMDrssHdvtRHccHMjR",
	"gWSZGWzGFhnFFgnhNsRHtRdsVjZcRjHs",
	"jgplhpJJFgnDrrwfqprwDP",
	"CWhMSRfWhVVnRSZnVVdsLQqQMzGqLBvGMQqczv",
	"PHbpNwrjJplttvcclLlQzzDszc",
	"NrJbJrFNNJNPrmwrtbjtNmCfSWfWhSZZfSWCsfShfFVR",
	"VLhRPLGLRPRSStRRLwfGqfmDwbmqbqqDlD",
	"rBSFvppnzTbwDwlDcFWm",
	"MJrnJTMvMsrTsPtshRNPZdSLhL",
	"BZBrRCrnCQBBnZfGqhGGMMRcthMhMG",
	"TLjsCdDCPTvNssjdsPsDgsgqGcPHczchtHczWzPWzzlWhG",
	"gsTpsdNbvNNjNSpsNDTsmCnSVQFmSFwZnQBnmnQQ",
	"llbsNsWrmbrGbWCNtBjcCFBzQFZBCFjF",
	"LdSpwgdqSgzwJdRdLMRHLjQQjHjFHctjHBDTZj",
	"gSppgpSJMhpzwrhblfbhhlWlnW",
	"DwhTvvsJZWsBnDzPpBLbFp",
	"GHtNGRGNdzbMBBtmBt",
	"NljlCSVSHdjGSQRGlCQSCswqfWzhZfTcfzcJvshJ",
	"lmsGNFsDGqCbFQBbffjjwpzptw",
	"hRQdvdrvrvSngWnvnHrTMfzfzRtftzwVTwwpzB",
	"HnSSWrvLJvWJGFDsmFLPDFcQ",
	"bwwpGphpLghpTvpWphvJlFLJqqltjSjVlSStSR",
	"cmszZdDdBZzcNcDCDcNsmNMcqVjMJStFRJltVPVrlVPjVJll",
	"HcdmcCzzzQcHNcsCdpnGnhwGgnRggHvbbR",
	"CfMBbwBGbMbDCFrDvhFFDT",
	"mjzRjjRdSmjPnzFZgnnrTT",
	"cmSsVcHjLHTwMfLBpBpBwM",
	"whqqfZzgHvhSzzVNVDbpDbmbVbNpJD",
	"GcQFntGTCCcCTMCTGBlJsJsDDWpRbWBsJpNS",
	"FnPcrGFFdddMnCnTqgqgqPHfLjLqgSzz",
	"zMSzzjssFdGnszRtNftqqwFHbbZw",
	"RRPLVrgrwHqBqgwt",
	"rPWmLCTCQlCQQmmrWLrQShJshhzdhhJjcSjlzRds",
	"lvgvCDfPqLHppqpCCDJncbntttbBtBBVHjwtrB",
	"TdddszSQsWcngjzVbcVZ",
	"hRWsTRTGQhNRGhRTFSWmlpgfqlvLmplPqvvGgv",
	"LbWFLQdWWPwWSjSHPHRfppHHDRpggR",
	"zmqqNNzlzmnzzNCmVCmtBzpfGsfpBgDgspprcfcfsrRB",
	"qNNVNJtNmmmNzznVJzvCTDZWhvZZjZFbWQQhFhbZSw",
	"DjdHqJVVhHVZjhDHPWtDtZLFBRBFmSRTFSbwmRRTffTTJf",
	"NNznnGlgMQsnQzNclzpfSRSMRmfPMmFRwBwB",
	"vzrcGcNcPPvHvHPt",
	"wLCcmZwWTNtZNdMSMGSCnJGGMB",
	"RFbHsPhVvFPRjlshhrnQnGjQGSdSqJfqnQBM",
	"HhzVlFHhPwzScmSTgL",
	"TNlBhDNvNBFpJgpPPpDQ",
	"jjfCdCZZqsCZsbdqPgFGGMRzSFMqQMRS",
	"jnWPtWssCtWcmZbbtstvnrrvhVBhTNNhBHlBlL",
	"DZwNWPDzPVWbJngrQjrNnrQcMg",
	"GRRfttLBhhvTvmLmFcFcgFFSnjWrnsrG",
	"TLthBWtTRLHqhlLLfmhBqVPDJVdPwzJCPPZHwdDdVd",
	"GGVhrVSMQwQqfVssVvnWFgvgWn",
	"jtlcRBBtQRmpWsjzFCvzWnvF",
	"QPcRbpppDmNDtPPblZMfhZdDwdMrqSSGrq",
	"ZRrdtBdQvQsWnnfWFZsF",
	"bJLcMzNDLbMgwfnGMWFv",
	"lpvhmzNDmDmlNbzbmrVVPrHRCPHQBVCP",
	"rZllQrsRWrlQswccMVbGbVbTdcQQ",
	"NtJCntLSHCjznfLTcGGGqWMdWM",
	"jCtzzSFthhSSSjPJrFDlvWrlDZRpwpRZ",
	"mQmbLjbrLQjLmTtwwWBTTvWjtt",
	"BHSqdHclHHNFlppNqWPwfwDvTfDPPtCw",
	"ddSGMGHcdcMhMZnBbmbZmgGJJg",
	"lvvBzvDnlzjfPnfjnQPlldRbVbRqbqqCgsqqVpQQgVqc",
	"NNFtGNMtTNFmJNGNZtZMwVRTTcsCpVTbbgCbgRhscp",
	"FGNGZMtNLWmmJWGFWJGLSNtPrPnBfDzzvjnDBzpnvDBLnv",
	"fwvQRFQvQqwpwNJrwN",
	"BstDnBjhjBhnshSptpJzWqNppbfr",
	"CsDjCdZcBCDcjnfDHfhnfggZMGlgQVmgMTRmgVGMMl",
	"MwlBVqVlsgnmzwJsvjhWZhGPvjvRRWzG",
	"QNQpQpftHdHHCHGfSpCrQNdSrDRDhchhjvjcPrRRWrPvhZjv",
	"LtLSCTSGfHGdGwswnqsggssTqV",
	"qDDCHjzjznTvWshZQWfnZZ",
	"PFFmmNMMtNMVFtczcFPJNrLhZwQZQsSvvSvWvGQQJQssss",
	"tFzrrPPNNFlzVrpRTpblRDqjTpDC",
	"DWDrrBdpmdpBrCgDthdtfcHsqJsCqscqwfsjzHcq",
	"TNLNFNSTQNQTSnlMcczVJjVzsqLDDfJJ",
	"TFPZQRvvlMSPPtRWDtmDRWrBGr",
	"LWGVZdrvWdpLGWRsjPMsHmdHdHldlj",
	"zJzznChzzzCSfTgMhCPDmlDCbmlsmjDDQj",
	"nSTTJhJtnShNtzwhgNrGRRWZZRvMWMtVrqGp",
	"PbPmtNmBbPlqBvqlDJBT",
	"LpGVDzVpVZqqSTvq",
	"pMnWGLRLRppnGpGndrGPtgDCjMPmbPgCQmPPNN",
	"sqcZcbZZpcZspcCCRMmznWGWdLWhwDRGTTWggT",
	"NjFSJgVHrvfVtrGzWdSznDwLSTLn",
	"jFrBNVVjBFNvHrFHBlBFFpMslPgPcpMPmcQPPZCgpP",
	"frddqsThtsTfTbPcvhsrbsRLpRBNRpmDpGmRGcRNLpGp",
	"QWJHCJwWzlHZQZHQCJJRzRqnLDGRGpnGBRnNDN",
	"CVwHCClJjQgWCZVZQgMwSdthjrqvrSPPhdbqtPhs",
	"TvdphBBhhhCgdLNNJJJLWz",
	"fVcsqRVrPcnJWgDnJN",
	"JlqsRJtssZwqwVtPwltRPsHHbFTwTFbpjHhQjTQbvpTF",
	"cQSnPDDQJGNzwnNpZb",
	"RHDrssVRDHRgsRFHRlrVwzzpNGZlfZdppZdwGNZb",
	"sHCHtDgtCjVVLFChqPMhBCMcSTqB",
	"hdbQbqcCCQcqFbCbVdcWCQQlRMBtGlRHBtBMpHhpHThZMR",
	"LLsSLLfgJPrgPnssnmlZtlZpHGHVGfZVtZpl",
	"PvmvgmvvnzmrSsSLJDqDNzqFDQdDwzWWbV",
	"HNNjnLbpLGHvWJDhdWWPpWDW",
	"lVcSNgcSVclhRlPZPRCDCR",
	"cqmSQrwwrrVSrtQFqVNmFwjQnvjHzBbLLGjfjzHTzvnH",
	"QmvWVppPHQQvbbvmSHSpPzfzwnWMTZFFzwFMCzLnwT",
	"jGBljlNNjgDtGDrNjjtjqqDRnMzRLnFzCFnMfRfMzCnttF",
	"jqNrrGdJcdgLjqDqBrDQbbmhdQQmmpPbphmbVv",
	"ZHQCggVHHRDWvbfjGptVtLvL",
	"nnFwnwrDDMShnhFrFLLLpjvPlPGGtLGb",
	"dcNSMhrrTDCBCsWgCTQW",
	"HqDDLGtDdCnhfDnwnV",
	"PmlJsJTPlbdBTzTnzhnnCCWWzV",
	"lSPjMScggsScgjSMMbqHLFGrRLGHRZZtdrcG",
	"ZVVtNNppdZSdLtCPqnHhqJJFtb",
	"zgwwQBfwmGgSrDfgrrGBggzHCnbJbqbCJFnqhHBhnHHCqJ",
	"rvrzfmlRrgDgmrzfggvwzvdjjcccLjMjVcVcsVLjVSZR",
	"dppcLRHpphchhNhSddjzHzWQWQLtrMsrWQCWCsMZssCZ",
	"JGfBfJJfBqvGVlVbDBwDBDBfZnrQsMQtssMttssDsQMWZncn",
	"qPVwlgPBmjpPhcmS",
	"zGPnzBgPzPnPlHZlDDHnZBNCvrtcjcjmMcFzNcNFmFdc",
	"qQpfsLTTSspqTfJdmdCtMjdtjvJcmr",
	"bfQqqSrswLLrfpLTqprfTnDVDVBBbgHPDHnhDPgDbV",
	"JssTnsdFztZLdNJnNtTsLNZGqlbGFBqrGMHqHBcFBqMFMH",
	"CCgSfgPSvSfhpShSRppCdfrlqGHGGcHmclmqbbqbqlPc",
	"wvVSVjQSSQhRVvfQChvZZsdtJstjLNLZDJnLss",
	"CmfNNNZNqDrnDjMhZM",
	"gdczzGtdFcddtWQgGGMnVhnjJwnrJFDPTwMP",
	"dlvcdzdHtzQSLRSfmhLSqv",
	"ZpFFLcHFZZRRmJVZgD",
	"PzhrtQntzcrjCRJtbtRgBsBRVR",
	"zdzWfCzhQzlhWfWhlvpFNlpSqcMSHHMv",
	"NrrMgMhNQhNjQrtqtPtwVtZpggPw",
	"TfRLndnLFCRFTFbbRDHwpVqqBBwsHwZsfH",
	"TJFRdLlRThrlcvZcvQ",
	"scrwRVjbQvQBzsBC",
	"gMfVqNnVmnCBQDTvdn",
	"SMqhWqVlmWSmqMVRSJjjpcFrcLpJrR",
	"HtSQHQntHsHMrtHnGfHQVVzLvSBSVvVVSFNJzzVN",
	"cmPRmpqlpPmcgTlTpjJNjjVDvDRFNVVBFD",
	"hlmCpmqmpgqpZTlcdQHFQfbHHZttwMQwtr",
	"VpWgbgfwCjbftwVPPpGQFQhzTBQTBGPzqFTS",
	"dbRbDcRrsnsRrLZmLRDZldDZqTNTGqqFFzGGhSTNTFTzNmNT",
	"MlLdHlDDHrHclMMrCwgHCCwWwCbCCjjg",
	"GGNLhfDMVcVrcGsT",
	"jSJQFjHbwPFSvQSHwZFvHSHrqCCrrTsqBwNBrcBNsVTsqq",
	"QjZSjZJZPvNRZJQPnSZbJZRWLfnmgDlmhdhWgWLdMdfmhM",
	"CgGnzPNggCJtNTgTZTPZzZZvvcDcDDdqDFcJssJDHDqvHq",
	"jhhrrLVlmLRRnRflfVbFHHHqdVsDqcvbHVDb",
	"jWfWwrlmRRnQmPzZNGZPBNCQTB",
	"NzDDhwNmhvtrGmNCvWRVbcRRVTcHHcVFTbwV",
	"LgsPlLsQgQdJsLdldtpgFFTMbnFqTcMbHqFcPncq",
	"dgsJsLLLggljrhtGNNtSjvGm",
	"ptzSrZtzhsmmtPrhLFRFnjnnLMsnfLRL",
	"HvwVDHwWWgGDGdHgqVDWDMnRnTjFNTNjfLJvRRRRRR",
	"DwDgWgQbDDDHwBBBWdwQGVHhlhlZZSSmztfcppSBhzZcZp",
	"CWmWRzlMJqWDWqCJbqDlCBBVLMQHVMGrfMVtQZrsLL",
	"SnhPdFFPNZsBBdHtVQ",
	"SSPcFFgnwnSpwvcSjwzCqRzTmJbpJCRBmbbD",
	"wQbqGWWSqwrbGWWWGjbNMJPfgfnnDmPnPNLfjN",
	"tJFztRZCvVRCztZFZRVgmMhmgNLfRfnmDPNPhm",
	"BFCVZzpVFlHCdbQqcTcGlJbbSG",
	"tttfLPZZQZTlZPHHPWgMVvBnjmvjnjgGBQ",
	"FzcNDDDrNzprrrshprhFJtVGVnjtjGvnhvVnnjnjGM",
	"RDqJNszDPfdqPtlT",
	"QCJdMjCQbdBjSbTHDsbWDDwHTP",
	"zlvlmqzqGfgdNzLldrHwwPGpWDrPGZWprr",
	"gfVfRczVqcRzmdcSQMjQSQCSjQCQ",
	"RhhCGhRBShjjRfpwppFTfFHZHZZD",
	"qzdqzlnPPctPdmtPdTZbwQvvwqvHHvZpwZ",
	"nVTVTcsWmWSRhhRVrGVB",
	"GmshRMnzqRGsPNwMwcrrpcVV",
	"CDCbFCLvCgfDSFLslgDpwpLtTwwcPtNNtTTprt",
	"JvSFbSbbFllJlgDvlJbgdRhRdqzBGnzshZnRRRnHBZ",
	"ShJhtcsvvvQbnnsccVTLVTppWqddpVnLWp",
	"NdzPrPZgPMNNrmzpTzpTCjWfzCpzVL",
	"dZgHmZRPPZRlZmrPDtDRccvbtQQbJbRS",
	"wqjLjwhznhBLqLWGfvSlvcmlrJsqrtJTJJ",
	"PwbpFPQDRCDrDJTrTmvs",
	"gbZVFbZHgwHbCdpCRMnffNLhWnnzMdzLLW",
	"RVVGSNTTRlNqHblBNB",
	"JfwJMvLLZwLsMJwWMJfwLHBqzFlvzpBQcqzblFbBqblq",
	"wMCZJsgJCCCnsMHrgLLjSPSVTgShtRjTPhRRmt",
	"lmQSSWdMHHLWgWqD",
	"ZZtVGGGJrJvGVCwfgHNLccmNFFcqtc",
	"vrCGPhvrTPdRBnsRTmmp",
	"dDMDDjzCQjwCCcDgjSLLLsLNlmpplN",
	"FqrHFTFRLCLVFBmS",
	"JhHJhHRThrfPZPvhnTZZbWdwdwDDWtDzJDtbMtCW",
	"ghwDzJRDwHmPthncSPncLLsPcvnv",
	"MWCrNTCHrMVjQQMQcSdnpTLnFFdTcnTc",
	"qbWMfWfNrWVQWfbjVBbqMfwDtqzmhmRRzGhtHhHhRwZh",
	"fmSmnjTjrlzGlTzJdH",
	"BrhRRQMrgQvgFFhQQbwpFvGGdZqZJqpJqHVpJGJLHdLJ",
	"ggbDwQMsvsMQrFMFcWSPSCPmSsPfnnmP",
	"cmNVbMrrrjcHDRcvfW",
	"wQGdFfSThFsLhhHWvDCWDCJRCCjd",
	"LtpStGhqrrpnfnpp",
	"bvcccTqbgvpGndJtgdsgNd",
	"wDQwQhtQhQRmSmjsJndJdBBJBJnlLS",
	"hwhmRrzFVjtwzDmrVFrvPCcCMVPPvfqpCCTVVb",
	"jRrRNPNRWjPRWPRQNjQjThTCzBBzDCFBGzgDFGGQ",
	"dnppLwmwCnvtlqltvtnTGBThGhdFZhgzDzGccD",
	"MvnqpLlMqCqCHMjWPPHMSHSs",
	"NNpNNvpvBdtTrMFFMhSSwzjzchzwhzwL",
	"VVndHqflQZZZgHSLLhjzRSmZRhcR",
	"glGgnqbQlngnWCGJpJprtrtFrdPPGs",
	"WqwRjzGtRzZZRRGjWBJzjwmfMTHGGssTTDsrLmmmQLMD",
	"SNdvSdFlSNNhSPFFcPFclbQQslHmfHTDsTQMLgDTmHQQ",
	"CNcCFvpdnWpjWwJf",
	"PVPnVHcnRncGZqbVzHVPnnLbSMjwrzWMjSwDtWwWtwWhwDWz",
	"pTfsQCshCllpglWWSjBMSQSrMrjM",
	"hvpvppggCpJTvTmshgfsmZRRHqbcLPHZmPLRnmPZ",
	"LQbhVZZmZhZjBdbGmgHqnHTmvqgnnWHr",
	"SzCfDFFNRfsSFFMFfvprvpWzqzgqTwHTvp",
	"CDNDFJgMDSQhjVdPJLQG",
	"plpdLdpjjrrHJJjLrrHLFdbzzCcvzgFgcwggzPMFvvcMhM",
	"GRtSBQNsQlMPRzRlzw",
	"ZSTtsmBlmjLLpnpH",
	"hglGNVSdNSghzSgCBhDFLBMBtFMMFtHtbtLL",
	"frQZccRcqGFmFHrJ",
	"nvfGZwvTwGTfQwvfTwfgnCSlpdnzgzslppCsCV",
	"snTSPbQnTTnQgbmsTJsLfZwjffhpLnGRjpGfjL",
	"dcNWcNHHlNtWHHlCtltWNFNMLZwjpGfpmrZfrFprrRGpwZfp",
	"HmdNWCmDMVvQPDgqJs",
	"GGFtSngQLfnSnQffgPnRgFRGRwmRJvwbBbJDwjvTbjrwhJvJ",
	"WHClslcNNWcqNWlCZdcHsVrThBwBjbhDTDBhrvDZJTwm",
	"NWVqqcHHNpsNcNVdVlhCMlHQQMQQzLfzQPttFGPMLSLgtF",
}
